server:
  port: 8082
  servlet:
    context-path: /products

spring:
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: 5672
    username: "${RABBITMQ_USER:pica}"
    password: "${RABBITMQ_PASS:Pica2020++}"
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_PRODUCT_QUERY_HOST:localhost}:3302/productquerydb
    username: product
    password: product2020++

events:
  amqp:
    queue: products-queue-command
  rpc:
    exchange: images-exchange-events
    queue: image-queue-query
    routing-key: images-events-key

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
    org.springframework.amqp: DEBUG
    co.edu.javeriana.products: DEBUG
