server:
  port: 8081
  servlet:
    context-path: /products

spring:
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: 5672
    username: "${RABBITMQ_USER:pica}"
    password: "${RABBITMQ_PASS:Pica2020++}"
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_PRODUCT_COMMAND_HOST:localhost}:3301/productcommanddb
    username: product
    password: product2020++
  #jackson:
  #  serialization:
  #    WRITE_DATES_AS_TIMESTAMPS: false

events:
  amqp:
    exchange: products-exchange-events
    queue: products-queue-command
    routing-key: products-command-key
  dead-letter:
    exchange: products-exchange-deadletter
    queue: products-queue-deadletter
    routing-key: products-deadletter-key

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
    org.springframework.amqp: DEBUG
    co.edu.javeriana.products: DEBUG